---
title: "Instacart Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

library(flexdashboard)
library(plotly)
```

```{r}
data("instacart")

instacart =
  instacart %>% sample_frac(.5) %>% 
  select(-add_to_cart_order, -reordered, -eval_set, -order_number, -days_since_prior_order, -aisle_id, -department_id) %>% 
  mutate(
    order_dow = recode(order_dow, '0' = "Sunday", '1' = "Monday", '2' = "Tuesday", '3' = "Wednesday", '4' = "Thursday", '5' = "Friday", '6' = "Saturday"), 
    order_dow = factor(order_dow,  levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>% 
  group_by(order_dow, order_hour_of_day) %>% 
  summarize(num_orders = n()) %>% 
  mutate(text_label = str_c("Hour: ", order_hour_of_day, "\nDay: ", order_dow, "\nOrders: ", num_orders)) %>% 
  plot_ly(
    x = ~order_hour_of_day, 
    y = ~num_orders,
    color = ~order_dow,
    type = "scatter",
    mode = "lines",
    text = ~text_label,
    colors = "viridis"
  ) %>% 
  layout(
    title = "When are most people shopping?",
    xaxis = list(title = "Hour of Day"),
    yaxis = list(title = "Number of Orders")
)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>% 
  count(department) %>% 
  mutate(department = fct_reorder(department, n)) %>% 
  plot_ly(
    x = ~department, y = ~n, color = ~department, type = "bar", colors = "viridis") %>% 
  layout(
    title = "Order Numbers by Department",
    xaxis = list(title = "Department"),
    yaxis = list(title = "Number of Orders")
  )
```

### Chart C

```{r}
instacart %>% 
  filter(department == "snacks") %>% 
  mutate(aisle = forcats::fct_reorder(aisle, order_hour_of_day)) %>% 
  plot_ly(
    y = ~order_hour_of_day, 
    color = ~aisle, 
    type = "violin", 
    box = list(visible = T),
    meanline = list(visible = T),
    colors = "viridis") %>% 
  layout(
    title = "Snack Purchases by Time of Day",
    xaxis = list(title = "Snack Aisle"),
    yaxis = list(title = "Hour of Day")
  )
```

